package org.gaozou.roy.quick.dialog;

/**
 * Author: george
 * Powered by GaoZou group.
 */
public class AboutDialog extends javax.swing.JDialog {
    /** Creates new form AboutDialog */
    public AboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        setBounds(150, 150, 360, 280);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();

        getContentPane().setLayout(null);

        setTitle("About");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 24));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Quick");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 30, 160, 50);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 10));
        jLabel2.setText("v 0.1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 70, 60, 20);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel3.setText("");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 140, 130, 15);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 10));
        jLabel4.setText("Goege\u00e1n\n<gaozou18@gmail.com>");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 160, 270, 20);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12));
        jLabel5.setText("");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 100, 270, 15);

        closeButton.setFont(new java.awt.Font("Dialog", 0, 12));
        closeButton.setText("Close");
        closeButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        getContentPane().add(closeButton);
        closeButton.setBounds(210, 200, 80, 20);

        pack();
    }//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new AboutDialog(new javax.swing.JFrame(), true).show();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

}
